---
title: "read_results_cluster"
editor_options: 
  chunk_output_type: console
---

```{r libs}
# library(MASS)
# library(matrixcalc)
# library(Matrix)
library(tidyr)
library(ggplot2)

library(fabletools)
library(fable)
library(feasts)
library(tsibble)
library(dplyr)

# library(devtools)
# load_all()
library(ReconCov)
library(purrr)
```


# Read

```{r}
S <- readRDS("tourism/data/S.rds")
row_names <- readRDS("tourism/data/row_names.rds")
seq_dates <- readRDS("tourism/job/seq_dates.rds")
visnights_full <- readRDS("tourism/data/visnights_full.rds")

path <- "D:/Github/tourism_cluster/results/" # new results

M <- 133

result_list_full <- list()
for (i in 1:M) {
  if (i == 19) next # iteration 19 has error
  result <- readRDS(paste0(path, "result_", i, ".rds")) 
  # result_list[[i]] <- result
  result_list_full[[i]] <- result[-3] # not taking the base fitted models
}
result_list <- result_list_full[-19]

# remove the last 3 years of results
M <- M - 3*12 - 1 # -1 for the removed iteration 19
result_list <- result_list[1:M]

# flatten out the sublist in `e`
flatten_e_list <- function(e_list) {
  out <- list()

  for (name in names(e_list)) {
    obj <- e_list[[name]]

    if (is.list(obj) && all(vapply(obj, is.matrix, logical(1)))) {
      ## e.g. name == "mint_shr_pc", obj contains K1 … K20
      for (k in names(obj)) {
        out[[paste(name, k, sep = "_")]] <- obj[[k]]   # “mint_shr_pc_K1”, …
      }
    } else {
      out[[name]] <- obj                               # “base”, “ols”, …
    }
  }
  out                                             # all matrices at top level
}
all_model_names <- names(flatten_e_list(result_list[[1]]$e))


h <- 12
# model_names <- c("base", "ols", "mint_shr", "mint_n")
SSE_cum <- setNames(
  lapply(all_model_names, function(name) {
    matrix(0, h, length(rownames(S)), dimnames = list(1:h, rownames(S)))
  }),
  all_model_names
)
# wrangle
# SSE_cum <- Reduce(function(acc, res) Map(`+`, acc, res$e2),
#                       result_list, init = SSE_cum)

# need to square the errors first
SSE_cum <- Reduce(
  function(acc, res) {
    e_flat <- flatten_e_list(res$e)
    Map(function(x, y) x + y^2, acc, e_flat[ names(acc) ])   # element-wise matrix addition
  },
  result_list,
  init = SSE_cum
)

  
# W_shr_store <- sapply(result_list, `[[`, "W_shr")
# W_n_store <- t(sapply(result_list, `[[`, "W_n")) ; colnames(W_n_store) <- c("lambda", "delta")

MSE <- lapply(SSE_cum, function(mat) mat / M)
```



# Evaluation

## Average plots

```{r}
MSE_ts <- transform_sim_MSE(MSE, F)

# MSE plot
MSE_ts |> group_by(.model, h) |>
  summarise(mse = mean(MSE)) |>
  filter(.model != "mint_sample") |> 
  ggplot(aes(x = h, y = mse, color = .model)) +
    geom_line() +
    labs(x = "Horizon", y = "MSE") +
    theme_minimal()

# % improv plot
MSE_ts |>
  # filter models
  # filter(.model %in% c("base", "ols", "mint_shr", "mint_n")) |>
  # filter(!grepl("K10|K20", .model)) |>
  # filter(grepl("mint_n", .model)) |>
  group_by(series, h) |>
  mutate(
    base_MSE = MSE[.model == "base"]
  ) |>
  ungroup() |>
  group_by(.model, h) |>
  summarise(
    MSE = mean(MSE),
    base_MSE = mean(base_MSE),
    pct_change = (MSE - base_MSE) / base_MSE * 100
  ) |>
  ggplot(aes(x = h, y = pct_change, color = .model)) +
  geom_line() +
  labs(x = "Horizon", y = "% improvements",
       title = "% relative improvements in MSE compared to Base",
       subtitle = "training size = 120, iterations = 96") +
  theme_minimal()
```

```{r}
improv_overtime <- matrix(0, 96, length(all_model_names),
  dimnames = list(1:96, all_model_names)
)

for (i in 1:96) {
  res <- result_list[[i]]
  for (model in model_names) {
    if (model == "base")
      improv_overtime[i, model] <- mean(res$e2[[model]][1,])
    else
      improv_overtime[i, model] <- (mean(res$e2[[model]][1,]) - improv_overtime[i, "base"]) / improv_overtime[i, "base"] * 100
  }
}

improv_overtime[, 2:4] |>            # keep the three models
  as.data.frame() |>
  cbind(Month = seq_dates$end) |> 
  pivot_longer(-Month,
               names_to  = "model",
               values_to = "pct_improve") |> 
  ggplot(aes(x = Month, y = pct_improve, color = model)) +
    geom_line() +
    labs(x = "Month", y = "% improvements",
         title = "% relative improvements in average error squared compared to Base for each iteration") +
    theme_minimal()

```


## At each level

```{r}
series <- rownames(S)

level_index <- set_names(
  vector("list", 8),
  c(
    "Australia", "State", "Zone", "Region",
    "Australia_by_Purpose", "State_by_Purpose", 
    "Zone_by_Purpose", "Region_by_Purpose"
  )  
)
level_index$Australia <- which(series == "Total")
level_index$State <- which(series %in% names(state_map))
level_index$Zone <- which(series %in% names(zone_map))
level_index$Region <- which(series %in% unlist(state_map, use.names = F))

# find indices for series by purpose
series_split <- strsplit(series, " - ")
purposes <- c("Business", "Holiday", "Visiting friends and relatives", "Other reason")
level_index$Australia_by_Purpose <- which(series %in% purposes)
level_index$State_by_Purpose <- which(
  sapply(series_split, function(x) length(x) == 2 && 
         x[1] %in% names(state_map))
)
level_index$Zone_by_Purpose <- which(
  sapply(series_split, function(x) length(x) == 2 && 
         x[1] %in% names(zone_map))
)
level_index$Region_by_Purpose <- which(
  sapply(series_split, function(x) length(x) == 2 && 
         x[1] %in% unlist(state_map, use.names = F))
)


# similar to for key, value in dict.items() in Python
level_map <- imap(level_index, function(value, key){
  set_names(rep(key, length(value)), series[value])
}) |> 
  flatten_chr()

desired_order <- c(
  "Australia", "Australia_by_Purpose",
  "State",     "State_by_Purpose",
  "Zone",      "Zone_by_Purpose",
  "Region",    "Region_by_Purpose"
)
```

```{r}
# MSE at each level
MSE_ts <- MSE_ts %>% 
  mutate(
    level = level_map[series] %||% NA_character_,
    # %||% is just “if lookup returns NULL, fall back to NA
    level = factor(
      level,
      levels = desired_order,
      labels = str_replace_all(desired_order, "_", " ")  # replace "_" with " "
    )
  )

# % improv plot by level
MSE_ts |>
  # # # filter models
  # filter(!grepl("K10|K20", .model)) |>
  # filter(!grepl("mint_shr", .model)) |> 
  # filter(.model == "base" | grepl("K1", .model)) |>
  filter(.model %in% c("base", "ols", "mint_n", "mint_shr")) |>
  group_by(series, h) |>
  mutate(
    base_MSE = MSE[.model == "base"]
  ) |>
  ungroup() |>
  group_by(.model, level, h) |>
  summarise(
    MSE = mean(MSE),
    base_MSE = mean(base_MSE),
    pct_change = (MSE - base_MSE) / base_MSE * 100
  ) |>
  filter(.model != "mint_sample") |> 
  ggplot(aes(x = h, y = pct_change, color = .model)) +
    geom_line() +
    labs(x = "Horizon", y = "% improvements",
         title = "% relative improvements in MSE compared to Base") +
    facet_wrap(~ level, ncol=2, scales = "free_y") +
    theme_minimal()
```

# Probabilistic Evaluation

## Get winkler & CRPS score

```{r}
library(distributional)


M <- length(result_list_full)


# List of Winkler scores for each model
#   row - CV iterations
#   col - series
all_model_names <- all_model_names[!grepl("K5|K10|K20", all_model_names)] # remove pc models
result_winklers_80 <- setNames(
  lapply(all_model_names, function(name) {
    matrix(0, M, length(rownames(S)), dimnames = list(1:M, rownames(S)))
  }),
  all_model_names
)
result_winklers_95 <- result_winklers_80
result_cprs <- result_winklers_80

# Get actual data
y <- visnights_full |> 
  as_tibble() |> 
  arrange(State, Region) |>
  left_join(row_names, by = c("State", "Zone", "Region", "Purpose")) |>
  select(name, Nights, Month) |>
  pivot_wider(names_from = name, values_from = Nights) |>
  select(-Month) |>
  as.matrix()
y <- y[, rownames(S)]

vectorise_winkler <- function(mu, sd, actual, interval) {
  if (length(mu) == 0 || length(sd) == 0) {
    stop("mu or sd empty")
  }
  sapply(
    rownames(S),
    function(series) winkler_score(
      dist_normal(mu[series], sd[series]),
      actual[series],
      interval
    )
  )
}

vectorise_crps <- function(mu, sd, actual) {
  if (length(mu) == 0 || length(sd) == 0) {
    stop("mu or sd empty")
  }
  sapply(
    rownames(S),
    function(series) CRPS(
      dist_normal(mu[series], sd[series]),
      actual[series]
    )
  )
}

start_date <- seq_dates$start[1]

for (i in 1:M) {
  
  if (i == 19) next # iteration 19 has error
  result <- result_list_full[[i]]
  result$e <- flatten_e_list(result$e) # flatten the list of errors
  resid <- result$resid

  actual <- y[seq_dates$end[i] + 1 - start_date + 1, ] # 1-step ahead actuals

  # Recover a list of W1_hat for each model
  W1_hats <- list()
  W1_hats[["base"]] <- cov(resid) # sample variance of 1-step-ahead residuals as a proxy
  W1_hats[["ols"]] <- W1_hats[["base"]]
  W1_hats[["mint_shr"]] <- shrinkage_est(resid, result$W_shr[1])$cov
  W1_hats[["mint_n"]] <- novelist_est(resid, result$W_n["delta", 1], result$W_n["lambda", 1])$cov
  rownames(W1_hats[["mint_n"]]) <- colnames(W1_hats[["mint_n"]]) <- rownames(S)
  # pc models
  W1_hats[["mint_shr_pc_K1"]] <- shrinkage_pc_est(resid, 1, result$W_shr[2])$cov
  W1_hats[["mint_shr_pc_K2"]] <- shrinkage_pc_est(resid, 2, result$W_shr[3])$cov
  W1_hats[["mint_n_pc_K1"]] <- novelist_pc_est(resid, 1, result$W_n["delta", 2], result$W_n["lambda", 2])$cov
  W1_hats[["mint_n_pc_K2"]] <- novelist_pc_est(resid, 2, result$W_n["delta", 3], result$W_n["lambda", 3])$cov

  for (model in all_model_names) {
    if (model == "base") {
      base_fc <- actual - result$e$base[1, ] # recover 1-step ahead base forecast

      # Winkler score for base model
      result_winklers_80[[model]][i, ] <- vectorise_winkler(
        base_fc, sqrt(diag(W1_hats[["base"]])), actual, 80
      )
      result_winklers_95[[model]][i, ] <- vectorise_winkler(
        base_fc, sqrt(diag(W1_hats[["base"]])), actual, 0.95
      )
      # CRPS for base model
      result_cprs[[model]][i, ] <- vectorise_crps(
        base_fc, sqrt(diag(W1_hats[["base"]])), actual
      )

    } else {
      # obtain mapping G
      if (model == "ols") {
        G <- solve(t(S) %*% S) %*% t(S)
      } else {
        P <- t(S) %*% solve(W1_hats[[model]])
        G <- solve(P %*% S) %*% P
      }
      # get reconciled forecast and covariance
      y_recon <- actual - result$e[[model]][1, ]
      W1_recon <- S %*% G %*% W1_hats[[model]] %*% t(G) %*% t(S)

      # Winkler score for reconciled model
      result_winklers_80[[model]][i, ] <- vectorise_winkler(
        mu = y_recon, sd = sqrt(diag(W1_recon)), actual, 80
      )
      result_winklers_95[[model]][i, ] <- vectorise_winkler(
        mu = y_recon, sd = sqrt(diag(W1_recon)), actual, 0.95
      )
      # CRPS for reconciled model
      result_cprs[[model]][i, ] <- vectorise_crps(
        mu = y_recon, sd = sqrt(diag(W1_recon)), actual
      )
    }
  }
}

# remove 19th row
nrow(result_winklers_95[[1]])
result_winklers_80 <- lapply(result_winklers_80, function(mat) mat[-19, ])
result_winklers_95 <- lapply(result_winklers_95, function(mat) mat[-19, ])
result_cprs <- lapply(result_cprs, function(mat) mat[-19, ])

saveRDS(result_winklers_80, "tourism/job/results/result_winklers_80.rds")
saveRDS(result_winklers_95, "tourism/job/results/result_winklers_95.rds")
saveRDS(result_cprs, "tourism/job/results/result_cprs.rds")
```


```{r}
library(stringr)

result_winklers_80 <- readRDS("tourism/job/results/result_winklers_80.rds")
result_winklers_95 <- readRDS("tourism/job/results/result_winklers_95.rds")

winklers_df <- result_winklers_80 |> 
  transform_sim_MSE(F) |> 
  # change column name "h" to "iter", "MSE" to "score"
  rename(iter = h, score = MSE)

# add level
winklers_df <- winklers_df %>% 
  mutate(
    level = level_map[series] %||% NA_character_,
    # %||% is just “if lookup returns NULL, fall back to NA
    level = factor(
      level,
      levels = desired_order,
      labels = str_replace_all(desired_order, "_", " ")  # replace "_" with " "
    )
  )

# filter last 3 years
winklers_df <- winklers_df %>%
  filter(iter <= M - 12*3 - 1) # keep only the first M iterations
```

```{r}
# winklers per model
winklers_df |> 
  group_by(.model) |>
  summarise(score = mean(score)) |>
  ggplot(aes(x = .model, y = score)) +
    geom_col() +
    labs(x = "Model", y = "Winkler score",
         title = "Average Winkler scores for each model") +
    theme_minimal()

# winklers improvements per model
winklers_df |>
  group_by(series, iter) |>
  mutate(
    base_score = score[.model == "base"]
  ) |>
  ungroup() |>
  group_by(.model) |>
  summarise(
    score = mean(score),
    base_score = mean(base_score),
    pct_change = (score - base_score) / base_score * 100
  ) |> 
  ggplot(aes(x = .model, y = pct_change, fill = .model)) +
    geom_col() +
    labs(x = "Model", y = "% improvements",
         title = "% relative improvements in Winkler score (80) compared to Base",
         subtitle = "Interpret: negative values indicate improvement") +
    theme_minimal()

# winklers improvements per model per level
winklers_df |>
  group_by(series, iter) |>
  mutate(
    base_score = score[.model == "base"]
  ) |>
  ungroup() |>
  group_by(.model, level) |>
  summarise(
    score = mean(score),
    base_score = mean(base_score),
    pct_change = (score - base_score) / base_score * 100
  ) |> 
  ggplot(aes(x = .model, y = pct_change, fill = .model)) +
    geom_col(position = "dodge") +
    labs(x = "Level", y = "% improvements",
         title = "% relative improvements in Winkler score (95) compared to Base",
         subtitle = "Interpret: negative values mean improvement") +
    facet_wrap(~ level, ncol=2, scales = "free_y") +
    theme_minimal()
```


```{r}
# average of % improvements per series
winklers_df <- winklers_df |>
  group_by(series, iter) |>
  mutate(
    base_score = score[.model == "base"]
  ) |>
  ungroup() |>
  mutate(pct_change_per_series = (score - base_score) / base_score * 100)
  
winklers_df |> 
  group_by(.model) |> 
  summarise(
    pct_change_avg = mean(pct_change_per_series)
  ) |> 
  ggplot(aes(x = .model, y = pct_change_avg, fill = .model)) +
    geom_col() +
    labs(x = "Model", y = "% improvements",
         title = "Average of % relative improvements in Winkler score (80) compared to Base",
         subtitle = "Interpret: negative values indicate improvement") +
    theme_minimal()

winklers_df |> 
  group_by(.model, level) |> 
  summarise(
    pct_change_avg = mean(pct_change_per_series)
  ) |> 
  ggplot(aes(x = .model, y = pct_change_avg, fill = .model)) +
    geom_col(position = "dodge") +
    labs(x = "Level", y = "% improvements",
         title = "Average of % relative improvements in Winkler score (80) compared to Base",
         subtitle = "Interpret: negative values mean improvement") +
    facet_wrap(~ level, ncol=2, scales = "free_y") +
    theme_minimal()  
```



```{r}
# lolipop plots
winklers_df |> 
  group_by(series, level, .model) |> 
  summarise(
    pct_change_avg = mean(pct_change_per_series)
  ) |> 
  filter(level == "Region") |>
  ggplot(aes(x = series, y = pct_change_avg)) +
    geom_segment(aes(xend = series, yend = 0), color = "grey") +
    geom_point(aes(color = .model), size = 2) +
    # coord_flip() +
    theme(axis.text.y = element_blank()) +
    # facet_wrap(~ level, ncol=2, scales = "free_y")
    theme_minimal()
```