---
title: "read_results"
editor_options: 
  chunk_output_type: console
---


```{r libs}
# library(MASS)
# library(matrixcalc)
library(Matrix)
library(tidyr)
library(ggplot2)

library(fabletools)
library(fable)
library(feasts)
library(tsibble)
library(dplyr)

# library(devtools)
# load_all()
library(ReconCov)
library(purrr)
library(stringr)
source("R/helpers.R")
library(fmsb) # radarplot
library(tibble)
```

# Load and Wrangle

```{r}
path <- "sim/thesis_sim/"
# file <- "S4_2_1_T50_M500.rds"
file <- "S100_10_3_1_dense_T300"

result_list <- readRDS(paste0(path, file, "_M500.rds"))
h <- 4
M <- 500

params <- readRDS(paste0(path, "params_", strsplit(file, "_T")[[1]][1], ".rds"))
S <- params$S
T <- strsplit(strsplit(file, "_T")[[1]][2], "_")[[1]][1] |> as.integer()

# flatten out the sublist in `e`
flatten_e_list <- function(e_list) {
  out <- list()

  for (name in names(e_list)) {
    obj <- e_list[[name]]

    if (is.list(obj) && all(vapply(obj, is.matrix, logical(1)))) {
      ## e.g. name == "mint_shr_pc", obj contains K1 … K20
      for (k in names(obj)) {
        out[[k]] <- obj[[k]]   # “mint_shr_pc_K1”, …
      }
    } else {
      out[[name]] <- obj                               # “base”, “ols”, …
    }
  }
  out                                             # all matrices at top level
}

all_model_names <- names(flatten_e_list(result_list[[1]]$e))
series_names <- rownames(S)
SSE_cum <- setNames(
  lapply(all_model_names, function(name) {
    matrix(0, h, length(series_names), dimnames = list(1:h, series_names))
  }),
  all_model_names
)

# we only plot these models
model_names <- all_model_names[!grepl("K5|K10|K20|sample", all_model_names)]

# # need to square the errors first
# SSE_cum <- Reduce(
#   function(acc, res) {
#     e_flat <- flatten_e_list(res$e)
#     Map(function(x, y) x + y^2, acc, e_flat[ names(acc) ])   # element-wise matrix addition
#   },
#   result_list,
#   init = SSE_cum
# )
# MSE <- lapply(SSE_cum, function(mat) mat / M)
```


```{r}
# average across series per iteration -> compute % improv per iter -> average across iter
# result_df stores % improv per iter for each model, horizon
result_df <- tibble(
  .model = character(0),
  iter = integer(0),
  h = integer(0),
  MSE = numeric(0),
  pct_change = numeric(0)
)

for (i in 1:length(result_list)) {
  e_list <- flatten_e_list(result_list[[i]]$e)
  # average across series for base model
  base_MSE <- rowMeans(e_list$base^2)
  for (model in model_names) {
    # average across series each horizon, iteration
    model_MSE <- rowMeans(e_list[[model]]^2)
    pct_change <- (model_MSE - base_MSE) / base_MSE * 100
    result_df <- rbind(
      result_df,
      tibble(
        .model = rep(model, length(model_MSE)),
        iter = rep(i, length(model_MSE)),
        h = 1:length(model_MSE),
        MSE = model_MSE,
        pct_change = pct_change
      )
    )
  }
}
```


# Plotting

## Point
```{r}
# MSE_ts <- transform_sim_MSE(MSE, F)

# # % improv plot
# # average first, then compute % change later
# cap <- 5
# plot_df <- MSE_ts |>
#   # filter(.model %in% c("base", "ols", "mint_shr", "mint_n")) |>
#   filter(.model %in% model_names) |>
#   # filter(.model != "hresid_mint_n_hcov") |>
#   group_by(series, h) |>
#   mutate(
#     base_MSE = MSE[.model == "base"]
#   ) |>
#   ungroup() |>
#   group_by(.model, h) |>
#   summarise(
#     MSE = mean(MSE),
#     base_MSE = mean(base_MSE),
#     pct_change = (MSE - base_MSE) / base_MSE * 100
#   ) |>
#   encode_recon_models() |> 
#   # cap pct_change upper 10%
#   mutate(
#     capped = pct_change >= cap,
#     capped_pct_change = pmin(pct_change, cap)
#   )

# plot_df |> 
#   ggplot(aes(x = h, y = capped_pct_change, color = family, shape = shape_lab, linetype = variant_type)) +
#     geom_line(linewidth = 1.2) +
#     geom_point(alpha = 0.85, size = 2.6, na.rm = TRUE) +
#     recon_scales +
#     # label actual values for capped points
#     geom_text(
#       data = subset(plot_df, pct_change >= cap),
#       aes(label = round(pct_change, 1)),
#       vjust = -0.5, color = "black", size = 3
#     ) +
#     theme_minimal() +
#     labs(
#       x = "Forecast Horizon", y = "% improvements",
#       title = paste(
#         "Average of % relative improvements in MSE compared to Base.", 
#         strsplit(file, "_M")[[1]][1]
#       ),
#       subtitle = "Interpret: negative values indicate improvement. Avg over series and iterations"
#     )

# # compute % per series first, then average
# MSE_ts |>
#   filter(.model %in% c("base", "ols", "mint_sample", "mint_shr", "mint_n")) |>
#   # filter(grepl("mint_n", .model)) |>
#   group_by(series, h) |>
#   mutate(
#     base_MSE = MSE[.model == "base"],
#     pct_change_each = (MSE - base_MSE) / base_MSE * 100
#   ) |> 
#   ungroup() |>
#   group_by(.model, h) |>
#   summarise(
#     pct_change = mean(pct_change_each)
#   ) |> 
#   ggplot(aes(x = h, y = pct_change, color = .model)) +
#     geom_line() +
#     theme_minimal()

```

```{r}
# consistent % improv:
# Compute MSE across series each iterations → % improv each iterations → average across 500 iterations

plot_df <- result_df |> 
  filter(.model %in% model_names) |>
  group_by(.model, h) |>
  summarise(
    MSE = mean(MSE),
    pct_change = -mean(pct_change) # inverse for improvement
  ) |>
  encode_recon_models()

cap <- -6
plot_df <- plot_df |> 
  # cap pct_change upper 10%
  mutate(
    capped = pct_change <= cap,
    capped_pct_change = pmax(pct_change, cap)
  ) 

plot_df |>
  ggplot(aes(x = h, y = capped_pct_change, color = family, shape = shape_lab, linetype = variant_type)) +
    geom_line(linewidth = 1.2) +
    geom_point(alpha = 0.85, size = 3.5, na.rm = TRUE) +
    recon_scales +
    # label actual values for capped points
    geom_text(
      data = subset(plot_df, pct_change <= cap),
      aes(label = round(pct_change, 1)),
      vjust = -0.5, color = "black", size = 3
    ) +
    theme_minimal() +
    labs(
      x = "Forecast Horizon", y = "% improvements",
      title = paste(
        "Average of % relative improvements in MSE compared to Base.", 
        strsplit(file, "_M")[[1]][1]
      ),
      subtitle = "Interpret: negative values indicate improvement. Avg across %improv from 500 iterations"
    )
```


## Probabilistic

```{r}
path <- "sim/thesis_sim/"
file <- "S100_10_3_1_dense_T300"
score_list <- readRDS(paste0(path, "scores_", file, "_M500.rds"))

get_score_df <- function(mat) {
  score_df <- mat |> 
    transform_sim_MSE(F) |> 
    # change column name "h" to "iter", "MSE" to "score"
    rename(iter = h, score = MSE)
  
  # wrangle
  # filter pc2 models
  score_df <- score_df |> 
    filter(.model != "base_shr") |> 
    filter(.model != "mint_sample")
  # % improvements per series
  score_df <- score_df |>
    group_by(series, iter) |>
    mutate(
      base_score = score[.model == "base"]
    ) |>
    ungroup() |>
    mutate(pct_change_per_series = (base_score - score) / base_score * 100) # positive is improvement

  encode_recon_models(score_df) |> 
    select(-method_raw, -shape_lab, -linetype_lab, -variant_type)
}
score_df <- get_score_df(score_list$w80) |> mutate(rule = "W80")
score_df <- rbind(score_df, get_score_df(score_list$w95) |> mutate(rule = "W95"))
score_df <- rbind(score_df, get_score_df(score_list$crps) |> mutate(rule = "CRPS"))

# Consistent plotting:
# average across series per iteration -> compute % improv per iter -> average across iter
score_df <- score_df |> 
  group_by(rule, iter, family, model_label, pc_k) |>
  summarise(
    score = mean(score),
    base_score = mean(base_score),
    pct_change = (base_score - score) / base_score * 100
  ) |>
  ungroup() |>
  # average across iter
  group_by(rule, family, model_label, pc_k) |>
  summarise(
    mean_score = mean(score),
    pct_change_avg = mean(pct_change)
    # # capped at 10%
    # pct_change_avg = pmin(pct_change_avg, 10),
    # capped = ifelse(pct_change_avg >= 10, 1, 0)
  ) |>
  # filter unwanted models
  filter(!grepl("Base-S|OLS-S|sample", model_label))

{
  energy_df <- score_list$energy[,1:11] |> 
    as_tibble(rownames = "iter") |>
    pivot_longer(-iter, names_to = ".model", values_to = "score") |>
    mutate(iter = as.integer(iter))
  # pct change
  energy_df <- energy_df |> 
    group_by(iter) |>
    mutate(
      base_score = score[.model == "base"],
      pct_change_per_series = (base_score - score) / base_score * 100
    ) |> 
    # filter unwanted models
    filter(.model != "mint_sample") |>
    encode_recon_models() |> 
    filter(!grepl("Base-S|OLS-S|sample", model_label)) |> 
    group_by(family, model_label, pc_k) |>
    summarise(
      mean_score = mean(score),
      pct_change_avg = mean(pct_change_per_series)
    )
  
  energy_df <- energy_df |> 
    mutate(rule = "Energy") |> 
    select(rule, everything())
}

score_df <- score_df |> 
  rbind(energy_df)
```

```{r WS and CRPS}
# Consistent plotting:
# average across series per iteration -> compute % improv per iter -> average across iter
score_label <- "CRPS"
score_df |> 
  filter(rule == score_label) |>
  ggplot(aes(x = model_label, y = pct_change_avg, fill = family, alpha=pc_k)) +
    geom_col(color = "black", size = 0.5) +
    scale_alpha_manual(values = c("0" = 1, "1" = 0.7, "2" = 0.4), guide = "none") +
    labs(x = "Model", y = "% improvements",
         title = paste("Average of % relative improvements in", score_label, "compared to Base", strsplit(file, "_M")[[1]][1]),
         subtitle = "Interpret: negative values indicate improvement. Consistent avg and % improv") +
    # labels on top of bars if capped
    # geom_text(aes(label = ifelse(capped == 1, "> 10%", "")), vjust = -0.5) +
    recon_fill_scale +
    theme_minimal()
```

```{r Energy}
# overall energy score per model
score_df |>
  filter(rule == "Energy") |>
  ggplot(aes(x = model_label, y = pct_change_avg, fill = family, alpha=pc_k)) +
    geom_col(color = "black", size = 0.5) +
    scale_alpha_manual(values = c("0" = 1, "1" = 0.7, "2" = 0.4), guide = "none") +
    recon_fill_scale +
    labs(x = "Model", y = "% improvements",
         title = "Average of % relative improvements in Energy Score compared to Base",
         subtitle = paste(file)
        ) +
    theme_minimal()

```


### Radarplot

```{r}
# ----- consistent % improv -----
radar_df <- score_df |> 
  filter(.model %in% c("ols_shr", "mint_shr", "mint_n", "mint_shr_pc_K1", "mint_n_pc_K1")) |>
  # average across series per iteration & compute % improv per iter
  group_by(model_label, rule, iter) |>
  summarise(
    score = mean(score),
    base_score = mean(base_score),
    pct_change = (score - base_score) / base_score * 100
  ) |>
  ungroup() |>
  # average across iter
  group_by(model_label, rule) |>
  summarise(
    pct_change_avg = mean(pct_change)
  ) |>
  ungroup() |>
  filter(model_label != "Base") |>
  pivot_wider(names_from = rule, values_from = pct_change_avg) |>
  column_to_rownames("model_label")

radar_df <- cbind(
  radar_df,
  Energy = energy_df |> 
    filter(.model %in% c("ols_shr", "mint_shr", "mint_n", "mint_shr_pc_K1", "mint_n_pc_K1")) |> 
    group_by(model_label) |> 
    summarise(
      mean_score = mean(score),
      pct_change_avg = mean(pct_change_per_series)
    ) |> 
    pull(pct_change_avg)
)



radar_df <- -radar_df # flip sign so larger is better outward

{# --- 2) Add required max/min rows for fmsb::radarchart ---
maxs <- apply(radar_df, 2, max, na.rm = TRUE)
mins <- apply(radar_df, 2, min, na.rm = TRUE)
mins <- pmin(mins, 0)  # ensure min is at most 0
# pad the scale a bit so polygons don’t touch edges
pad  <- 0.01 * (maxs - mins)
scale_top <- maxs + pad
scale_bot <- mins - pad

plot_df <- rbind(scale_top, scale_bot, radar_df)

# --- 3) Colors (one per method, in row order) ---
cols <- c("#7b7b7bff","#1B9E77", "#6A51A3", "#66A61E", "#E6AB02")[seq_len(nrow(radar_df))]

# --- 4) Draw radar chart ---
radarchart(
  plot_df,
  axistype = 1,
  pcol  = cols,
  pfcol = scales::alpha(cols, 0.20),
  plwd  = 2,
  plty  = 1,
  cglcol = "grey80", cglty = 1, cglwd = 0.8,
  axislabcol = "grey30",
  vlcex = 0.9
)

legend("topright", legend = rownames(radar_df),
       col = cols, lty = 1, lwd = 2, bty = "n", cex = 0.9)
}
# add title
title(main = paste("Radarplot of % improvements over Base", strsplit(file, "_M")[[1]][1]))
# subtitle
mtext("Scores are scaled to [0, max(-scores)], better improvement is further outward", side = 3, line = 0.5, cex = 0.8)
```
